import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const roboto = Roboto({
  weight: "900",
  display: "swap",
  subsets:["latin"]
});

export const metadata: Metadata = {
  title: "Spring-Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Navbar / >
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
